export const CUSTOM_LIST_REQUEST = "CUSTOM_LIST_REQUEST";
export const CUSTOM_LIST_SUCCESS = "CUSTOM_LIST_SUCCESS";
export const CUSTOM_LIST_FAIL = "CUSTOM_LIST_FAIL";

export const CUSTOM_DETAILS_REQUEST = "CUSTOM_DETAILS_REQUEST";
export const CUSTOM_DETAILS_SUCCESS = "CUSTOM_DETAILS_SUCCESS";
export const CUSTOM_DETAILS_FAIL = "CUSTOM_DETAILS_FAIL";

// export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
// export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
// export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const CUSTOM_CREATE_REQUEST = "CUSTOM_CREATE_REQUEST";
export const CUSTOM_CREATE_SUCCESS = "CUSTOM_CREATE_SUCCESS";
export const CUSTOM_CREATE_FAIL = "CUSTOM_CREATE_FAIL";
export const CUSTOM_CREATE_RESET = "CUSTOM_CREATE_RESET";

export const CUSTOM_UPDATE_REQUEST = "CUSTOM_UPDATE_REQUEST";
export const CUSTOM_UPDATE_SUCCESS = "CUSTOM_UPDATE_SUCCESS";
export const CUSTOM_UPDATE_FAIL = "CUSTOM_UPDATE_FAIL";
export const CUSTOM_UPDATE_RESET = "CUSTOM_UPDATE_RESET";

// export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
// export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
// export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
// export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

// export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
// export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
// export const PRODUCT_TOP_FAIL = "PRODUCT_TOP_FAIL";
